version: '3.7'

services:

  portainer:
      image: portainer/portainer
      restart: always
      container_name: "portainer"
      command: --templates http://templates/templates.json
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/portainer/data:/data
  aras:
      container_name: "secure-squid"
      restart: always
      build:
        context: "sercure-squid/"
      ports:
        - "3128:3128"
      network_mode: "host"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock